### ISSUE TITLE
mime/media type

### ISSUE THREAD

**Issue by marisademeglio** [w3c/sync-media-pub#10]
currently: `application/vnd.wp-sync-media+json`

Ivan's comments (from mailing list): What does `vnd.wp-` stand for? The media is really a mouthful. What about something like /grin+json?

**Comment by marisademeglio** [comment]
Comments originally from @danielweck  (?) extracted from the draft documents:

"Note that the `application/vnd.wp-sync-media+json` mime / media type (typically for the HTTP Content-Type header) used in the `encodingFormat` JSON property does not formally exist. Such value would need to be proposed for IANA registration (see <a href="https://www.iana.org/assignments/media-types/media-types.xhtml">IANA Media Types</a> ). To be discussed."

**Comment by marisademeglio** [comment]
@danielweck since you proposed `application/vnd.wp-sync-media+json`, i'm going to ask you - is there a requirement that our mime type name has to meet? could we pick something shorter or does it go against precedent? i wouldn't mind something a bit more memorable, unless there's a reason we shouldn't.

**Comment by danielweck** [comment]
I don't think we are married to a "vendor" prefix, but here is something to keep in mind:

https://www.iana.org/form/media-types
> Registrations in the standards tree must be approved by the IESG or must correspond to a formal publication by a recognized standards body.

The SMIL example:
https://www.iana.org/assignments/media-types/application/smil+xml
https://tools.ietf.org/html/rfc4536

@murata2makoto I believe you have some experience registering IANA types, is that correct?

**Comment by danielweck** [comment]
@murata2makoto I was being sarcastic :)
https://www.iana.org/assignments/media-types/application/epub+zip

**Comment by swickr** [comment]
For media types described by W3C specifications, see [How To] [Register an Internet Media Type for a W3C Spec](https://www.w3.org/2002/06/registering-mediatype2014)

**Comment by marisademeglio** [comment]
Something like `application/syncnarr+json` [1]  is both short and looks more or less the same level of readability (or non-readability) as the [examples here](https://www.w3.org/2002/06/registering-mediatype2014). 

And it says 
   W3C Community Groups may also request to register a provisional media type through W3C

Once we decide, I can start that process by emailing the appropriate people.

1.  "media" vs "narration" name pending, see #24

**Comment by murata2makoto** [comment]
Sorry for my belated reply.  Yes, I have some experiences.  Creating a new media subtype in the standard tree takes time.

Since this subtype is defined by a Draft Community Group Report , I think that a subtype in the vendor tree is easier.  In other words, I do not think that the standard tree provide enough advantages.

**Comment by marisademeglio** [comment]
Thanks @murata2makoto for your insight.

I'm proposing we use `application/vnd.syncnarr+json`. It aligns with our newly-decided name of "Synchronized Narration", it's in the vendor tree, and it's not too verbose. I believe this addresses all the concerns raised so far.
