### ISSUE TITLE
naming: "sync media" or "sync narration"

### ISSUE THREAD

**Issue by marisademeglio** [w3c/sync-media-pub#24]
The CG is, for short, "sync-media-pub", and people generally refer to our work as "Synchronized Media"; however, the most [recent draft report](https://w3c.github.io/sync-media-pub/narration.html) is actually called "Sync Narration", which was an attempt to be precise. We don't cover a very wide range of synchronized media scenarios; it's specifically applicable to content narration in alternate modalities. However, as everyone still says "Sync Media", should we just rename the report to that instead?

**Comment by mhakkinen** [comment]
I like the precision, but In the range of possible audio books, would there be instances of non-speech audio authored and synchronized as part of the narration.  What if it is a song book? Vocal music synchronized with textual lyrics, as part of a book containing traditional narration synchronized with.   

Sync Media seems to be more encompassing, so long as some of us don't start thinking we can include that media type which begins with "v".

**Comment by marisademeglio** [comment]
Good points - you can never tell how people are going to use your syntax. I think sign language video sync (being considered for version-next) could still reasonably be called "sync narration" but I also don't have a super strong opinion, and if "sync media" feels better to everyone (it seems to), then we might as well go with that.

**Comment by chrisn** [comment]
I'd recommend the more precise name... In the Media & Entertainment space, a "Synchronized Media" spec could well imply video, but also synchronization of A/V across multiple devices (as per the [Multi-device Timing CG](https://www.w3.org/community/webtiming/)).

**Comment by marisademeglio** [comment]
That's also a very good point, there's a lot of media territory that is outside of our scope.

**Comment by rdeltour** [comment]
just and idea: one purpose of the spec is to provide an _alternative_ rendering of the content, so maybe we can use it the word somewhere? (meet sam, synchronized alternative media).

**Comment by larscwallin** [comment]
Just a thought regarding the use of the "alternate" property, or indeed the idea of Sync Media as an alternative rendition. 
I expect that there will be many usages of this technology where the contents of the Sync Media is not a complete alternative to the document which it augments.

**Comment by marisademeglio** [comment]
> just and idea: one purpose of the spec is to provide an _alternative_ rendering of the content, so maybe we can use it the word somewhere? (meet sam, synchronized alternative media).

Sammy! I can't wait for the sandwich logo to drop. Deliciously synchronized layers...

**Comment by marisademeglio** [comment]
> Just a thought regarding the use of the "alternate" property, or indeed the idea of Sync Media as an alternative rendition.
> I expect that there will be many usages of this technology where the contents of the Sync Media resources do not represent complete alternative renditions of the documents that they augment.

FWIW: The name of the `alternate` property in [pub-manifest](https://w3c.github.io/pub-manifest/) comes from [rel-alternate](http://microformats.org/wiki/rel-alternate). 

I don't think it's a perfect term to use but it's also not the worst, and it has precedent. 

So far I've heard:

* Sync Media:  pros - generic; cons - generic.
* Sync Narration: pros - specific; cons - doesn't cover all potential uses.
* Sam: pros - catchier; cons - emphasizes 'alternative', which may not be the most precise term.

Anything else to add to this list? Should we vote? I would be enthusiastic about closing this issue and etching into stone a final decision.

**Comment by llemeurfr** [comment]
Let's have a vote then ...

I has been said before, an issue with Sync *Media* is its proximity (in the W3C) with terms like *Media* Queries and *Media* & Entertainment Activity. 

With Sync *Narration* we use a term which source is clearly the publishing culture. Plus, *narration* is one of the main properties in the JSON document representing the alternate rendition of the source content.

**Comment by chrisn** [comment]
Just to throw out another suggestion, the CG name uses "for publications" as a qualifier, so perhaps this could be used in the spec name?

**Comment by marisademeglio** [comment]
Voted via mailing list, decided on "Synchronized Narration".

https://lists.w3.org/Archives/Public/public-sync-media-pub/2019Nov/0016.html
