### ISSUE TITLE
Add root-level properties

### ISSUE THREAD

**Issue by marisademeglio** [w3c/sync-media-pub#29]
This should address two open issues:

#21 which points out that we can't define our styling classes via HTML `meta`
#26 (and #28) which seeks to clarify the HTML document URL

We may also consider adding an `audioFile` which would remove the verbosity of repeating the audio file name in each sync point, for the case where all the narration is in one audio file.

```
{
        "properties": {
            "sync-media-css-class-active": "-my-active-element",
            "sync-media-css-class-playing": "-my-document-playing",
            "htmlDocument": "content.html"
          },
        "narration": [
          {
            "text": "#id1",
            "audio": "audio.mp3#t=0.0,1.2"
          },
          {
            "text": "#id2",
            "audio": "audio.mp3#t=1.2,3.4"
          },
          ...]
}
```

**Comment by HadrienGardeur** [comment]
Instead of `htmlDocument`, could we align with the same generic approach than the rest of the document (`text`, `audio`)?

**Comment by marisademeglio** [comment]
You mean regarding the property names, e.g.:
```
{
        "properties": {
            "sync-media-css-class-active": "-my-active-element",
            "sync-media-css-class-playing": "-my-document-playing",
            "text": "content.html",
            "audio": "file.mp3"
          },
...
}
```
?

**Comment by danielweck** [comment]
I feel quite uneasy about a top-level ad-hoc override of the JSON document's "base" for specific properties (such as `text` or `audio`). I posted a more detailed comment in this issue:
https://github.com/w3c/sync-media-pub/issues/28#issuecomment-580489070

**Comment by marisademeglio** [comment]
So this is ok:
```
{
    "narration": [{
        "text": "file.html#p1"
        "audio": "chap.mp3#t30,40"
    }]
}
```

But this is not ok:

```
{
    "properties": {
        "textDoc": "file.html",
        "audioDoc": "chap.mp3"
    },
    "narration": [{
        "text": "#p1"
        "audio": "#t30,40"
    }]
}
```
? 

I have read your detailed comment and all the links. Could you walk me through where it gets ambiguous with a concrete example?

**Comment by marisademeglio** [comment]
This is not an issue in [the new draft](https://raw.githack.com/w3c/sync-media-pub/wip/docs/new/sync-media.html)
