### ISSUE TITLE
Sync Media Document structure

### ISSUE THREAD

**Issue by iherman** [w3c/sync-media-pub#37]
[§3.2](https://w3c.github.io/sync-media-pub/sync-media.html#document-structure) says: 

> A SyncMedia document contains two parts: a head and a body. 

In practice that looks o.k., but formally it is not: if we consider Sync Media as a version of SMIL (see also #35), then there is a `smil` element on top. That is actually so specified in [the content model](https://w3c.github.io/sync-media-pub/sync-media.html#content-model), and there is also a note in §5.1 about this, but I believe this should be made clear in this section right away. Also, all examples should be correct (ie, with a `smil` element on top) or the text should make it clear that the examples are _not_ to be considered as correct.

**Comment by marisademeglio** [comment]
Yep this is related to [delaying a serialization format decision](https://github.com/w3c/sync-media-pub/issues/38#issuecomment-749134162).

Also see the [note](https://w3c.github.io/sync-media-pub/sync-media.html#xml) here which acknowledges that the `smil` element has gone unmentioned thus far.
