### ISSUE TITLE
`text` referring to HTML only?

### ISSUE THREAD

**Issue by iherman** [w3c/sync-media-pub#39]
[§3.4 Media Objects](https://w3c.github.io/sync-media-pub/sync-media.html#media-objects) defines the value of `text` as 

> References text content in an HTML document.

I believe both SMIL and EPUB 3 are slightly different. 

SMIL is much more generic and refers to the [`smilText` module](https://www.w3.org/TR/SMIL/smil-text.html).  I understand if we do not want to go here, that would indeed be quite unnecessary. Probably we should make it clear that, although we take over a SMIL element, it is _restricted compared to its original definition_.

EPUB is a bit evasive and allows any textual content document, whatever that may be. Here is the [EPUB definition](https://w3c.github.io/epub-specs/epub33/core/#sec-smil-text-elem):

> A text element typically refers to a textual element but can also refer to other EPUB Content Document media elements (see [§ 7.3.2.3 Embedded Media](https://w3c.github.io/epub-specs/epub33/core/#sec-audio-video)).

One can follow one's nose through the references to get to [EPUB content documents](https://w3c.github.io/epub-specs/epub33/core/#sec-contentdocs). _As of today_, only XHTML would be the valid target for a Media Overlay `text` element, i.e., even HTML would not. I.e., Sync Media is more permissive in this respect because, at least in the current text, it does not restrict the target to be 'X'. However, if tomorrow EPUB introduces, say, markdown as an acceptable textual core content format or, more seriously, if the discussions in https://github.com/w3c/epub-specs/issues/636 lead to HTML being also allowed, then the situation would change. The latter would be in line with the current Sync Media spec, the former would not.

I would try to be more evasive in the current Sync Media. Something like "references textual document", maybe referring to some of the media types that are in the `text/` tree, or something similar. That would make it more robust for the future. (I must admit I am not sure how to express this properly.)

**Comment by marisademeglio** [comment]
Yes, that sounds good. I think we can just use SMIL [`text`](https://www.w3.org/TR/SMIL3/smil-extended-media-object.html#edef-text) as is, which is quite evasive. Maybe we can elaborate a little as you suggest and refer to some specific types of text. We can definitely stay away from SMIL's other text objects, `smilText` and `textstream`.
