### ISSUE TITLE
clock values

### ISSUE THREAD

**Issue by iherman** [w3c/sync-media-pub#40]
At the moment, the definition of `clipBegin` and `clipEnd` refer to [§B](https://www.w3.org/publishing/epub/epub-mediaoverlays.html#app-clock-examples) which lists a number of examples. 

However... `clipBegin` and `clipEnd` are not prefixed as `sync`, which means that these are _the_ SMIL attributes as defined in the SMIL Spec for [`clipBegin`](https://www.w3.org/TR/SMIL/smil-extended-media-object.html#adef-clipBegin) and [`clipEnd`](https://www.w3.org/TR/SMIL/smil-extended-media-object.html#adef-clipEnd), respectively. In SMIL, the value of these attributes refer to SMPTE or NPT and there is a "metric specifier" as part of the value. Looking at the examples in the SMIL spec, we have things like `clipBegin="smpte=10:12:33"` or `clipBegin="npt=123.45s"`.

I am not an expert in clock values, but there are questions here:

1. Do we want to keep this complexity in Sync Media? In which cases all the examples in [§B](https://www.w3.org/publishing/epub/epub-mediaoverlays.html#app-clock-examples) are syntactically wrong.
2. Do we want to choose among SMPTE or NPT, thereby simplifying the attribute (ie, no 'metric specifier')? Then this should be stated explicitly, and giving a proper definition to `clipBegin` and `clipEnd` as clock values.

If the choice is (2) (which sounds find to me) then what we have is _not_ the SMIL attribute anymore; we should not create an incompatibility (see also my comment in #35). Which would mean, in practice, to put both those attributes into the `sync` namespace.

**Comment by marisademeglio** [comment]
Agree we should formalize what we allow as clock values. I had, for now, punted on that, hence the Media Overlays reference.

I think though that conceptually we are a valid subset of SMIL, which says "If no metric specifier is given, then a default of "npt=" is presumed.".

I wonder if it would be beneficial to leave this unrestricted and accept (1) ? Since SyncMedia supports video, there might be some content creators who would want to use SMPTE frame-level references, whereas we didn't have to accommodate this in Media Overlays.

**Comment by iherman** [comment]
> 
> I think though that conceptually we are a valid subset of SMIL, which says "If no metric specifier is given, then a default of "npt=" is presumed.".
> 

Ah! I did not realize this (I am not really an expert in SMIL in spite of the fact that I still belong, formally, to the CWI department that has many of the SMIL editors on board:-). But sounds then good. 

> I wonder if it would be beneficial to leave this unrestricted and accept (1) ? Since SyncMedia supports video, there might be some content creators who would want to use SMPTE frame-level references, whereas we didn't have to accommodate this in Media Overlays.

I cannot really comment on that, not being an expert on using these...
