### ISSUE TITLE
Clip start/end points

### ISSUE THREAD

**Issue by iherman** [w3c/sync-media-pub#41]
In the Note at the end of [§3.4.1](https://w3c.github.io/sync-media-pub/sync-media.html#properties-2) the text refers to "clip start/end points"; I presume that it refers to the notions uses in the [Media Fragments spec](https://www.w3.org/TR/media-frags/#valid-uri-temporal). It would be better to make this explicit, thereby also making the note itself clearer.

**Comment by marisademeglio** [comment]
Agreed, good point!
