### ISSUE TITLE
The term `Tracks`

### ISSUE THREAD

**Issue by iherman** [w3c/sync-media-pub#42]
I am not sure I like the term ["Tracks"](https://w3c.github.io/sync-media-pub/sync-media.html#tracks); some of the examples, like using tracks to assign default properties to, e.g., texts, does not sound right to me for the generic term of 'tracks'.

Good topic for bikeshedding :-)

**Comment by marisademeglio** [comment]
Yes, the bikeshed is looking great already!

Defining properties on a `track` gives you a place to set high-level defaults, for example
- "always highlight this text
- "pan the sound effects track to the left"
- "play the background music at 50% volume"
- and more

`track` is similar to SMIL [`region`](https://www.w3.org/TR/SMIL3/smil-layout.html#edef-region) except that:
 - there's no visual rendering space defined
 - you can have a `defaultSrc` on a track (not required but often handy)
 - a track has a `trackType` indicating its purpose
 - a media object type can be automatically assigned to a track via `defaultFor` (again, not required but very useful)

The reason for not re-using `region` was that we felt our `tracks` were different enough, and if you start reading the SMIL section on `region`, it's easy to walk away with the impression that it always includes a visual definition.

That said, do any other words stand out as better candidates than `track`?

**Comment by iherman** [comment]
> The reason for not re-using region was that we felt our tracks were different enough, and if you start reading the SMIL section on region, it's easy to walk away with the impression that it always includes a visual definition.

Big +1 for not using `region`!

> That said, do any other words stand out as better candidates than track?

Wow. Expecting a non-native Anglo-Saxon speaker to come up with a good alternative? :-)

I looked at the [Webster](https://www.merriam-webster.com/thesaurus/track) which includes a number of synonyms, but nothing really stuck, though I was considering 'clue', or 'hint'...

Separately from Webster I was also wondering about 'plan'.

Naming is difficult:-)

**Comment by marisademeglio** [comment]
@larscwallin and I talked about this today and we have decided to stick with "track" and also to add some text to the explainer about how we see tracks affording "mixing" of different media streams, perhaps with an analogy to multitrack audio applications, to really help illustrate the concept.

**Comment by iherman** [comment]
Closing the issue
