### ISSUE TITLE
Visualizer not working

### ISSUE THREAD

**Issue by gbarreiro** [w3c/sync-media-pub#46]
Hello everybody! I'm trying out the demos in this repository, but the "visualizer" one (`/demo/visualizer`) is not working for me. I've just opened the `syncnarr.html` file and disabled the Cross-Origin and local file restrictions, but I just see this:

<img width="566" alt="Screen Shot 2021-02-18 at 10 06 54" src="https://user-images.githubusercontent.com/33569982/108333283-10ddb180-71d1-11eb-867e-7e67ad7d868f.png">

From the logs in the JS console of my browser, I deduced that the problems were due to the JavaScript scripts imported in the header. The two first ones (`highlight.min.js` and `svg.min.js`) were easily fixed by appending "https://" in the beginning of the URL. However, I'm not able to solve the `audiobooks.js`, `moment.js` and `vis.js` imports, since I can't find any of those JavaScript files in the repository. From where should I import them? Thank you in advance.

<img width="717" alt="Screen Shot 2021-02-18 at 10 11 46" src="https://user-images.githubusercontent.com/33569982/108333916-b6912080-71d1-11eb-9fdd-4d9d53474472.png">

**Comment by marisademeglio** [comment]
Ah sorry! The demos are kind of a mess at the moment, I didn't actually mean to add that folder just yet (but once I did I figured maybe that will pressure me into finishing it sooner than later!). The visualizer does work (for me) (locally), so I will see if I can post it later today.

**Comment by gbarreiro** [comment]
Excellent, thank you for your answer!

**Comment by marisademeglio** [comment]
@gbarreiro I made some updates, you can see the visualizer here: https://w3c.github.io/sync-media-pub/demo/visualizer/
