### ISSUE TITLE
Quick playback demo

### ISSUE THREAD

**Issue by danielweck** [w3c/sync-media-pub#6]
https://github.com/w3c/sync-media-pub/tree/master/samples/single-document

Maybe use this to simulate the experience?

https://github.com/thephilgray/custom-readaloud-plugin

The `data-playhead` attributes could be created after fetch + parse the overlay JSON.

**Comment by danielweck** [comment]
Quick-n-dirty implementation:
https://github.com/w3c/sync-media-pub/pull/19/files

Test URL:
https://raw.githack.com/w3c/sync-media-pub/feature/custom-read-aloud-player/samples/single-document/index.html

**Comment by marisademeglio** [comment]
Closing this to close things. We can keep our demos in a folder in this repo.
